PREFIX skos:<http://www.w3.org/2004/02/skos/core#>
PREFIX rdf:<http://www.w3.org/1999/02/22-rdf-syntax-ns#>
SELECT DISTINCT ?EDMO_CODE ?ORG_NAME ?COUNTRY WHERE {
	?EDMO_URL rdf:type <http://www.w3.org/ns/org#Organization>.
  	?EDMO_URL <http://www.w3.org/ns/org#name> ?ORG_NAME.
	?EDMO_URL skos:notation ?EDMO_CODE.
	?EDMO_URL <http://www.w3.org/2006/vcard/ns#country-name> ?COUNTRY.
} ORDER By ?ORG_NAME
